#!/usr/bin/env python3
"""
tools/generate_config.py -- derives EVERY number in the project from robot.yaml.

    python3 tools/generate_config.py [--check]

WHAT IT WRITES
    stm32/Core/Inc/minibot_config.h            firmware #defines
    ros2_ws/src/minibot_bringup/config/derived_params.yaml
    docs/DERIVED_NUMBERS.md                    the audit trail

WHY THIS EXISTS
    The same physical constants are needed by the STM32 firmware, ros2_control,
    Nav2's controller_server, Nav2's velocity_smoother, and the coverage planner.
    Five places. Hand-maintaining five copies is how you end up with a robot that
    "drifts" -- because the strictest layer silently clips the others and the
    planner never finds out.

    Generate them. Never hand-edit them.

    --check exits non-zero if the generated files are stale. Wire it into CI or
    your build and you can never ship a mismatched stack.
"""

import argparse
import math
import os
import sys
import hashlib

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANNER = "AUTO-GENERATED by tools/generate_config.py from robot.yaml -- DO NOT EDIT"


def derive(cfg):
    g, l, c, f = cfg['geometry'], cfg['limits'], cfg['coverage'], cfg['firmware']
    m = cfg['mass']

    d = {}
    d['wheel_radius'] = r = float(g['wheel_radius'])
    d['wheel_separation'] = L = float(g['wheel_separation'])
    d['robot_radius'] = R = float(g['robot_radius'])
    d['body_radius'] = float(g['body_radius'])

    # base_link sits at the WHEEL AXLE, i.e. wheel_radius above the ground.
    # The URDF needs sensor heights RELATIVE TO base_link, but you measure them
    # from the FLOOR. Convert here, once, so nobody has to remember to.
    d['lidar_z'] = float(g['lidar_height_from_ground']) - r
    d['imu_z']   = float(g['imu_height_from_ground']) - r

    # steps per WHEEL revolution
    d['steps_per_rev'] = spr = (float(g['motor_steps_per_rev'])
                                * float(g['microstepping'])
                                * float(g['gear_ratio']))

    rpm_max = float(l['max_wheel_rpm'])
    rpm_min = float(l['min_wheel_rpm'])

    # Linear
    d['v_max'] = v_max = 2 * math.pi * rpm_max / 60.0 * r
    d['v_min'] = v_min = 2 * math.pi * rpm_min / 60.0 * r

    # Angular: spin in place, both wheels at +/- v_max
    d['w_max'] = w_max = 2 * v_max / L
    d['w_min'] = w_min = 2 * v_min / L

    # Motion profile
    t_a = float(l['accel_time_s'])
    t_j = float(l['jerk_time_s'])
    d['a_max'] = a_max = v_max / t_a
    d['alpha_max'] = alpha_max = w_max / t_a
    d['jerk_max'] = a_max / t_j
    d['ang_jerk_max'] = alpha_max / t_j

    # Step domain (what the firmware actually clamps)
    d['max_step_rate'] = int(rpm_max / 60.0 * spr)
    d['min_step_rate'] = int(rpm_min / 60.0 * spr)
    d['max_accel_sps2'] = d['max_step_rate'] / t_a
    d['max_jerk_sps3'] = d['max_accel_sps2'] / t_j

    # HARD INVARIANT of the DDS pulse engine.
    # The step ISR drives STEP low at the top of the tick and high at the bottom.
    # If the phase-accumulator increment is < 0.5 (i.e. rate < ISR_HZ/2), it is
    # ARITHMETICALLY IMPOSSIBLE for two pulses to land on consecutive ticks --
    # which is what guarantees the DRV8825 gets its 1.9 us minimum LOW time.
    isr = int(f['isr_hz'])
    d['isr_hz'] = isr
    d['dds_ceiling'] = isr // 2
    if d['max_step_rate'] >= d['dds_ceiling']:
        sys.exit(
            f"FATAL: max_step_rate {d['max_step_rate']} >= ISR_HZ/2 "
            f"({d['dds_ceiling']}). The DRV8825 minimum low-time guarantee "
            f"breaks. Raise firmware.isr_hz or lower limits.max_wheel_rpm.")
    d['dds_headroom_pct'] = 100.0 * d['max_step_rate'] / d['dds_ceiling']

    # Timing
    d['spin_180_s'] = math.pi / w_max
    d['rad_per_step'] = 2 * math.pi / spr

    # ---- TORQUE CHECK -----------------------------------------------------
    # Small wheels MULTIPLY force: F = torque / radius. This is why 6 kg is easy
    # on 33.6 mm wheels and was impossible on the 190 mm wheels I wrongly assumed.
    T = float(m['motor_holding_torque_nm'])
    d['force_per_wheel'] = T / r
    d['force_total'] = 2.0 * T / r
    mass = float(m['robot_kg'])
    crr = float(m['rolling_resistance_coeff'])
    d['force_needed'] = mass * (crr * 9.81 + d['a_max'])
    d['torque_needed_per_wheel'] = (d['force_needed'] / 2.0) * r
    d['torque_margin'] = d['force_total'] / max(1e-9, d['force_needed'])
    # Traction ceiling: you cannot push harder than friction lets you.
    # mu ~= 0.7 for rubber on a hard floor; only the DRIVEN wheels carry it.
    d['traction_limit_n'] = 0.7 * mass * 9.81 * 0.6   # ~60% of weight on drive wheels
    d['limited_by'] = ('TRACTION (wheels will slip before the motor stalls)'
                       if d['traction_limit_n'] < d['force_total']
                       else 'MOTOR TORQUE')
    d['max_mass_kg'] = d['force_total'] / max(1e-9, (crr * 9.81 + d['a_max']))

    # Coverage
    d['erode_radius'] = R + float(c['safety_margin'])
    d['min_passable_gap'] = 2 * d['erode_radius']
    d['coverage_radius'] = float(c['cleaning_head_width']) / 2.0
    d['lane_spacing'] = float(c['lane_spacing'])

    # Lane spacing sanity: if lanes are wider than the brush, you leave stripes.
    head = float(c['cleaning_head_width'])
    d['head_width'] = head
    d['lane_overlap'] = head - d['lane_spacing']
    d['brush_gap'] = float(c['brush_separation']) - float(c['brush_diameter'])

    # THE WALL STRIP. The robot centre can never get closer to a wall than
    # erode_radius. The brush reaches half a head-width beyond that. Whatever is
    # left is NEVER CLEANED, and no software can fix it.
    d['wall_strip'] = d['erode_radius'] - head / 2.0

    # Costmap inflation must sit just above robot_radius. A cleaning robot MUST
    # be able to drive with its body a few cm off the wall -- that is the entire
    # point of the edge pass. Nav2's stock 0.70 m would make it unplannable.
    d['inflation_radius'] = R + 0.03

    return d


def fmt_header(cfg, d):
    f = cfg['firmware']
    s = cfg['serial']
    return f'''/* {BANNER} */
#ifndef MINIBOT_CONFIG_H
#define MINIBOT_CONFIG_H

/* ---- drivetrain -------------------------------------------------------- */
#define MB_STEPS_PER_REV      {d['steps_per_rev']:.1f}f
#define MB_WHEEL_RADIUS_M     {d['wheel_radius']:.6f}f
#define MB_WHEEL_SEP_M        {d['wheel_separation']:.6f}f

/* ---- motion envelope (derived from the RPM band in robot.yaml) ---------- */
#define MB_MAX_STEP_RATE      {d['max_step_rate']}            /* steps/s  */
#define MB_MIN_STEP_RATE      {d['min_step_rate']}            /* steps/s  */
#define MB_MAX_ACCEL_SPS2     {d['max_accel_sps2']:.1f}f      /* steps/s^2 */
#define MB_MAX_JERK_SPS3      {d['max_jerk_sps3']:.1f}f       /* steps/s^3 */

/*
 * MB_MAX_STEP_RATE ({d['max_step_rate']}) is {d['dds_headroom_pct']:.1f}% of the DDS ceiling
 * (ISR_HZ/2 = {d['dds_ceiling']}). Staying under that ceiling is what makes it
 * arithmetically impossible for two step pulses to land on consecutive ISR
 * ticks -- which is what guarantees the DRV8825 its 1.9 us minimum LOW time.
 * generate_config.py refuses to emit a header that violates it.
 */

/* ---- step engine ------------------------------------------------------- */
#define MB_ISR_HZ             {f['isr_hz']}u
#define MB_RAMP_HZ            {f['ramp_hz']}u
#define MB_FEEDBACK_HZ        {s['feedback_hz']}u

/* ---- safety ------------------------------------------------------------ */
#define MB_CMD_TIMEOUT_MS     {s['cmd_timeout_ms']}u
#define MB_IDLE_DISABLE_MS    {s['idle_disable_ms']}u

/* ---- wiring ------------------------------------------------------------ */
/* Robot spins instead of driving forward -> flip exactly ONE of these.
 * Robot drives backwards                 -> flip BOTH.                      */
#define MB_LEFT_DIR_INVERT    {f['left_dir_invert']}
#define MB_RIGHT_DIR_INVERT   {f['right_dir_invert']}

#endif /* MINIBOT_CONFIG_H */
'''


def fmt_params(cfg, d):
    s, sen, dk = cfg['serial'], cfg['sensors'], cfg['dock']
    c = cfg['coverage']
    return f'''# {BANNER}
#
# Included by every launch file. This is what keeps ros2_control, Nav2 and the
# coverage planner agreeing with the STM32 firmware.

/**:
  ros__parameters:
    # ---- geometry --------------------------------------------------------
    wheel_radius: {d['wheel_radius']:.6f}
    wheel_separation: {d['wheel_separation']:.6f}
    robot_radius: {d['robot_radius']:.6f}
    steps_per_rev: {d['steps_per_rev']:.1f}

    # ---- kinematic envelope (DO NOT exceed anywhere) --------------------
    max_linear_velocity: {d['v_max']:.6f}
    min_linear_velocity: {d['v_min']:.6f}
    max_angular_velocity: {d['w_max']:.6f}
    min_angular_velocity: {d['w_min']:.6f}
    max_linear_accel: {d['a_max']:.6f}
    max_angular_accel: {d['alpha_max']:.6f}

    # ---- serial ----------------------------------------------------------
    serial_device: "{s['device']}"
    serial_baud: {s['baud_rate']}

    # ---- coverage --------------------------------------------------------
    lane_spacing: {d['lane_spacing']:.4f}
    safety_margin: {float(c['safety_margin']):.4f}
    erode_radius: {d['erode_radius']:.4f}
    coverage_radius: {d['coverage_radius']:.4f}
    min_passable_gap: {d['min_passable_gap']:.4f}
    waypoint_spacing: {float(c['waypoint_spacing']):.4f}
    inflation_radius: {d['inflation_radius']:.4f}

    # ---- sensors ---------------------------------------------------------
    lidar_device: "{sen['lidar_device']}"
    lidar_max_range: {float(sen['lidar_max_range']):.2f}
    imu_i2c_bus: {sen['imu_i2c_bus']}
    imu_i2c_address: {sen['imu_i2c_address']}
    imu_rate_hz: {float(sen['imu_rate_hz']):.1f}

    # ---- dock ------------------------------------------------------------
    dock_x: {float(dk['x']):.4f}
    dock_y: {float(dk['y']):.4f}
    dock_yaw: {float(dk['yaw']):.4f}
'''


def fmt_doc(cfg, d):
    g, l, c, m = cfg['geometry'], cfg['limits'], cfg['coverage'], cfg['mass']

    ov = d['lane_overlap']
    ov_note = (f"{ov*100:.1f} cm per pass"
               if ov > 0.02 else
               f"**{ov*100:.1f} cm -- TOO TIGHT. You will leave uncleaned stripes.**")

    strip = d['wall_strip']
    gap = d['brush_gap']

    rpm_table = "\n".join(
        f"| {rpm} | {2*math.pi*rpm/60*d['wheel_radius']:.3f} m/s | "
        f"{int(rpm/60*d['steps_per_rev'])} sps | "
        f"{100*(rpm/60*d['steps_per_rev'])/d['dds_ceiling']:.1f} % |"
        for rpm in (20, 40, 60, 80, 100))

    return f"""# Derived numbers

{BANNER}

> ## :rotating_light: Revision 2 -- rebuilt from MEASURED hardware
> Revision 1 used `wheel_radius 0.19` and `wheel_separation 0.30`. **Both were
> wrong.** Every velocity, every Nav2 threshold and the whole URDF were wrong
> with them.
>
> | | Rev 1 (wrong) | **Measured** | Error |
> |---|---|---|---|
> | wheel radius | 0.1900 m | **{d['wheel_radius']:.4f} m** | **5.65x too big** |
> | wheel separation | 0.3000 m | **{d['wheel_separation']:.3f} m** | **33% too small** |
> | robot radius | 0.1900 m | **{d['robot_radius']:.3f} m** | wheels stick out past the body |

## Inputs (`robot.yaml`)

| | |
|---|---|
| wheel radius | **{d['wheel_radius']:.4f} m** ({2*d['wheel_radius']*1000:.1f} mm diameter, with rubber) |
| wheel separation | **{d['wheel_separation']:.3f} m** (centre-to-centre) |
| robot radius | **{d['robot_radius']:.3f} m** -- the WHEELS are the widest part, not the body |
| body radius | {d['body_radius']:.3f} m (visual only) |
| motor | {g['motor_steps_per_rev']} steps/rev x {g['microstepping']} microstep x {g['gear_ratio']} gear |
| wheel RPM band | {l['min_wheel_rpm']} .. **{l['max_wheel_rpm']}** |

## Kinematic envelope

| | |
|---|---|
| steps per wheel rev | **{d['steps_per_rev']:.0f}** |
| **distance per step** | **{2*math.pi*d['wheel_radius']/d['steps_per_rev']*1000:.4f} mm** -- your odometry resolution |
| linear velocity | {d['v_min']:.4f} .. **{d['v_max']:.4f} m/s** |
| angular velocity | {d['w_min']:.4f} .. **{d['w_max']:.4f} rad/s** |
| linear accel | {d['a_max']:.4f} m/s^2 |
| angular accel | {d['alpha_max']:.4f} rad/s^2 |
| **180 deg spin in place** | **{d['spin_180_s']:.2f} s** |
| step rate cap | **{d['max_step_rate']} sps** |

## :rotating_light: The RPM cap is the single biggest cost in the project

| RPM | speed | step rate | % of pulse engine |
|---|---|---|---|
{rpm_table}

At **{l['max_wheel_rpm']:.0f} RPM** the pulse engine is **{d['dds_headroom_pct']:.1f}% used** and the motors have
**{d['torque_margin']:.0f}x torque margin**. The cap is buying you nothing.
Change `limits.max_wheel_rpm` in `robot.yaml` and re-run this script -- the entire
stack (firmware clamps, ros2_control, Nav2, velocity_smoother) retunes itself.

## Torque check ({m['robot_kg']} kg robot)

| | |
|---|---|
| motor holding torque | {m['motor_holding_torque_nm']} N.m **(UNVERIFIED -- get your motor's datasheet)** |
| force per wheel | {m['motor_holding_torque_nm']} / {d['wheel_radius']:.4f} = **{d['force_per_wheel']:.1f} N** |
| total available | **{d['force_total']:.1f} N** |
| force needed at {m['robot_kg']} kg | {d['force_needed']:.2f} N |
| torque needed per wheel | **{d['torque_needed_per_wheel']:.4f} N.m** |
| **margin** | **{d['torque_margin']:.1f}x** |
| theoretical max mass | {d['max_mass_kg']:.0f} kg (torque-limited) |
| traction ceiling | ~{d['traction_limit_n']:.0f} N |
| **actually limited by** | **{d['limited_by']}** |

Small wheels **multiply force** (`F = torque / radius`). This is exactly why
{m['robot_kg']} kg is comfortable on {2*d['wheel_radius']*1000:.0f} mm wheels and would have been
*impossible* on the 380 mm wheels of revision 1.

## DDS pulse-engine invariant

| | |
|---|---|
| ISR rate | {d['isr_hz']} Hz |
| ceiling (ISR/2) | {d['dds_ceiling']} sps |
| used | **{d['dds_headroom_pct']:.1f} %** |

Staying below ISR/2 makes it *arithmetically impossible* for two step pulses to
land on consecutive ticks -- which is what guarantees the DRV8825 its 1.9 us
minimum LOW time. This script **refuses** to emit a config that breaks it.

## Cleaning geometry -- YOUR REAL BRUSHES

Two brushes, {float(c['brush_diameter'])*1000:.0f} mm diameter, centres {float(c['brush_separation'])*1000:.0f} mm apart.

| | |
|---|---|
| left brush covers | -0.150 .. -0.050 m |
| right brush covers | +0.050 .. +0.150 m |
| **total swept width** | **{d['head_width']:.2f} m** |
| **gap in the middle** | **{gap:.2f} m** |
| lane spacing | {d['lane_spacing']:.3f} m |
| lane overlap | {ov_note} |

> ### :warning: CONFIRM THE {gap*1000:.0f} mm MIDDLE GAP
> This is fine **only if your suction inlet sits there** (side brushes sweeping
> debris inward is the standard design). If there is nothing in the middle, you
> have a {gap*1000:.0f} mm uncleaned stripe down the centre of **every lane**, and
> no path planner can fix it.

> ### :warning: THE {strip*100:.0f} cm WALL STRIP -- a mechanical limit, not a software one
> The robot centre can never get closer than **{d['erode_radius']:.3f} m** to a wall
> (the wheels are the widest part). The brush reaches {d['head_width']/2:.3f} m beyond
> that -- so it stops **{strip*100:.0f} cm short of every wall**.
>
> Options: accept it; reduce `safety_margin` 0.03 -> 0.01 (strip becomes
> {(d['robot_radius'] + 0.01 - d['head_width']/2)*100:.0f} cm); or mount the brushes further outboard.

## Navigation geometry

| | |
|---|---|
| erosion radius | {d['erode_radius']:.3f} m |
| **min passable gap** | **{d['min_passable_gap']:.3f} m** -- narrower doorways are UNREACHABLE |
| costmap inflation | {d['inflation_radius']:.3f} m |
| lidar z (from base_link) | **{d['lidar_z']:.4f} m** (= {float(g['lidar_height_from_ground']):.3f} from ground - {d['wheel_radius']:.4f} axle height) |
| imu z (from base_link) | {d['imu_z']:.4f} m |

## Where these land

| Number | Consumer |
|---|---|
| `MB_MAX_STEP_RATE`, `MB_MAX_ACCEL_SPS2`, `MB_MAX_JERK_SPS3` | `stm32/Core/Inc/minibot_config.h` |
| `wheel_radius`, `wheel_separation` | `diff_drive_controller` (odometry), `base.xacro` |
| `v_max`, `w_max`, `a_max` | `diff_drive_controller`, Nav2 `FollowPath`, `velocity_smoother`, `behavior_server` |
| `robot_radius`, `inflation_radius` | Nav2 global + local costmaps |
| `erode_radius`, `lane_spacing`, `head_width` | `minibot_coverage` planner |
| `lidar_z`, `imu_z` | `lidar.xacro`, `imu.xacro` |
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if generated files are stale (for CI)')
    a = ap.parse_args()

    with open(os.path.join(ROOT, 'robot.yaml')) as f:
        cfg = yaml.safe_load(f)

    d = derive(cfg)

    outputs = {
        'stm32/Core/Inc/minibot_config.h': fmt_header(cfg, d),
        'ros2_ws/src/minibot_bringup/config/derived_params.yaml': fmt_params(cfg, d),
        'docs/DERIVED_NUMBERS.md': fmt_doc(cfg, d),
    }

    stale = []
    for rel, content in outputs.items():
        p = os.path.join(ROOT, rel)
        old = open(p).read() if os.path.exists(p) else None
        if old != content:
            stale.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                with open(p, 'w') as f:
                    f.write(content)

    if a.check:
        if stale:
            print('STALE (run tools/generate_config.py):')
            for s in stale:
                print('  ', s)
            sys.exit(1)
        print('config up to date')
        return

    print(f"wheel_radius {d['wheel_radius']:.4f} m ({2*d['wheel_radius']*1000:.1f} mm dia)  |  "
          f"sep {d['wheel_separation']:.3f} m  |  robot_radius {d['robot_radius']:.3f} m")
    print(f"v = {d['v_min']:.4f}..{d['v_max']:.4f} m/s   "
          f"w = {d['w_min']:.4f}..{d['w_max']:.4f} rad/s   "
          f"180deg spin {d['spin_180_s']:.2f} s")
    print(f"steps/rev {d['steps_per_rev']:.0f}  |  {2*math.pi*d['wheel_radius']/d['steps_per_rev']*1000:.4f} mm/step  |  "
          f"step cap {d['max_step_rate']} sps ({d['dds_headroom_pct']:.1f}% of DDS ceiling)")
    print(f"torque margin {d['torque_margin']:.1f}x at {cfg['mass']['robot_kg']} kg  "
          f"(limited by {d['limited_by']})")
    print(f"min passable gap {d['min_passable_gap']:.3f} m  |  "
          f"lidar z {d['lidar_z']:.4f} m from base_link")

    warn = []
    if d['dds_headroom_pct'] < 15.0:
        warn.append(
            f"RPM CAP: only {d['dds_headroom_pct']:.1f}% of the pulse engine is used and you "
            f"have {d['torque_margin']:.0f}x torque margin. max_wheel_rpm="
            f"{cfg['limits']['max_wheel_rpm']:.0f} is leaving a LOT on the table.")
    if d['lane_overlap'] <= 0.02:
        warn.append(f"LANE SPACING: only {d['lane_overlap']*100:.0f} cm overlap -> uncleaned stripes.")
    if d['lane_overlap'] > 0.08:
        warn.append(f"LANE SPACING: {d['lane_overlap']*100:.0f} cm overlap means you clean "
                    f"{100*d['lane_overlap']/d['head_width']:.0f}% of the floor TWICE. "
                    f"Raising lane_spacing would cut the run time.")
    if d['brush_gap'] > 0.02:
        warn.append(f"BRUSH GAP: {d['brush_gap']*100:.0f} cm between your two brushes. "
                    "Fine IF the suction inlet is there. Otherwise it is an "
                    "uncleaned stripe down the centre of every lane.")
    if d['wall_strip'] > 0.05:
        warn.append(f"WALL STRIP: the brushes stop {d['wall_strip']*100:.0f} cm short of every "
                    "wall. MECHANICAL limit -- no software fixes it.")
    if abs(d['robot_radius'] - d['body_radius']) > 1e-6:
        warn.append(f"The WHEELS ({d['robot_radius']*2*100:.0f} cm span) are wider than the BODY "
                    f"({d['body_radius']*2*100:.0f} cm). Nav2 uses {d['robot_radius']:.3f} -- correct.")
    if warn:
        print()
        for w in warn:
            print('  !! ' + w)

    print()
    for rel in outputs:
        print('  wrote', rel)


if __name__ == '__main__':
    main()
