lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['controller_server',
                 'planner_server',
                 'behavior_server',
                 'bt_navigator']
lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: false
    autostart: true
    node_names: ['map_server', 'amcl']
amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.05
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: scan
    max_beams: 180
    min_particles: 800
    max_particles: 3000
    update_min_d: 0.10
    update_min_a: 0.20
    resample_interval: 2
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    laser_model_type: "likelihood_field"
    laser_max_range: 12.0
    laser_min_range: 0.15
    z_hit: 0.95
    z_rand: 0.05
    sigma_hit: 0.2
    laser_likelihood_max_dist: 2.0
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.15
      movement_time_allowance: 60.0
    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.30
      yaw_goal_tolerance: 3.14
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.045
      lookahead_dist: 0.35
      min_lookahead_dist: 0.2
      max_lookahead_dist: 0.5
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.1
      transform_tolerance: 1.0
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.03
      approach_velocity_scaling_dist: 0.3
      use_collision_detection: false
      use_regulated_linear_velocity_scaling: true
      use_fixed_curvature_lookahead: false
      curvature_lookahead_dist: 0.25
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.6
      regulated_linear_scaling_min_speed: 0.03
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.6
      max_angular_accel: 1.0
      max_robot_pose_search_dist: 10.0
      stateful: true
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.19
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          obstacle_max_range: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.20
        cost_scaling_factor: 5.0
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      robot_radius: 0.19
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.20
        cost_scaling_factor: 5.0
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
behavior_server:
  ros__parameters:
    use_sim_time: false
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.5
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.2
    min_rotational_vel: 0.05
    rotational_acc_lim: 1.5
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/ubuntu/map/room_objects.yaml"
