/* AUTO-GENERATED by tools/generate_config.py from robot.yaml -- DO NOT EDIT */
#ifndef MINIBOT_CONFIG_H
#define MINIBOT_CONFIG_H

/* ---- drivetrain -------------------------------------------------------- */
#define MB_STEPS_PER_REV      3200.0f
#define MB_WHEEL_RADIUS_M     0.033600f
#define MB_WHEEL_SEP_M        0.400000f

/* ---- motion envelope (derived from the RPM band in robot.yaml) ---------- */
#define MB_MAX_STEP_RATE      1066            /* steps/s  */
#define MB_MIN_STEP_RATE      266            /* steps/s  */
#define MB_MAX_ACCEL_SPS2     2132.0f      /* steps/s^2 */
#define MB_MAX_JERK_SPS3      14213.3f       /* steps/s^3 */

/*
 * MB_MAX_STEP_RATE (1066) is 5.3% of the DDS ceiling
 * (ISR_HZ/2 = 20000). Staying under that ceiling is what makes it
 * arithmetically impossible for two step pulses to land on consecutive ISR
 * ticks -- which is what guarantees the DRV8825 its 1.9 us minimum LOW time.
 * generate_config.py refuses to emit a header that violates it.
 */

/* ---- step engine ------------------------------------------------------- */
#define MB_ISR_HZ             40000u
#define MB_RAMP_HZ            1000u
#define MB_FEEDBACK_HZ        50u

/* ---- safety ------------------------------------------------------------ */
#define MB_CMD_TIMEOUT_MS     500u
#define MB_IDLE_DISABLE_MS    10000u

/* ---- wiring ------------------------------------------------------------ */
/* Robot spins instead of driving forward -> flip exactly ONE of these.
 * Robot drives backwards                 -> flip BOTH.                      */
#define MB_LEFT_DIR_INVERT    1
#define MB_RIGHT_DIR_INVERT   0

#endif /* MINIBOT_CONFIG_H */
